// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuestLog.Infrastructure.Data;

#nullable disable

namespace QuestLog.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813184400_AddXpTransactions")]
    partial class AddXpTransactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuestLog.Domain.Entities.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-4000-8000-000000000001"),
                            Category = 0,
                            Description = "Complete any habit for the first time",
                            Icon = "🔥",
                            Key = "first_flame",
                            Name = "First Flame"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-4000-8000-000000000002"),
                            Category = 0,
                            Description = "Maintain a 7-day streak on any habit",
                            Icon = "⚔️",
                            Key = "week_warrior",
                            Name = "Week Warrior"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0003-4000-8000-000000000003"),
                            Category = 0,
                            Description = "Maintain a 30-day streak on any habit",
                            Icon = "🛡️",
                            Key = "monthly_master",
                            Name = "Monthly Master"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0004-4000-8000-000000000004"),
                            Category = 0,
                            Description = "Maintain a 100-day streak on any habit",
                            Icon = "👑",
                            Key = "century_club",
                            Name = "Century Club"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0005-4000-8000-000000000005"),
                            Category = 1,
                            Description = "Complete your first goal",
                            Icon = "🎯",
                            Key = "goal_getter",
                            Name = "Goal Getter"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0006-4000-8000-000000000006"),
                            Category = 1,
                            Description = "Complete 10 goals",
                            Icon = "🏆",
                            Key = "overachiever",
                            Name = "Overachiever"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0007-4000-8000-000000000007"),
                            Category = 1,
                            Description = "Complete 5 goal milestones",
                            Icon = "📌",
                            Key = "milestone_marker",
                            Name = "Milestone Marker"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0008-4000-8000-000000000008"),
                            Category = 1,
                            Description = "Complete at least one habit every day for 7 consecutive days",
                            Icon = "⭐",
                            Key = "perfect_week",
                            Name = "Perfect Week"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0009-4000-8000-000000000009"),
                            Category = 2,
                            Description = "Complete habits 5 days in a week",
                            Icon = "📅",
                            Key = "dedicated",
                            Name = "Dedicated"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0010-4000-8000-000000000010"),
                            Category = 2,
                            Description = "Complete habits 20 days in a month",
                            Icon = "🗓️",
                            Key = "committed",
                            Name = "Committed"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0011-4000-8000-000000000011"),
                            Category = 2,
                            Description = "Complete habits 100 total times",
                            Icon = "💪",
                            Key = "unstoppable",
                            Name = "Unstoppable"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0012-4000-8000-000000000012"),
                            Category = 2,
                            Description = "Reach Level 10",
                            Icon = "🌟",
                            Key = "rising_star",
                            Name = "Rising Star"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0013-4000-8000-000000000013"),
                            Category = 3,
                            Description = "Complete a habit after midnight (UTC)",
                            Icon = "🦉",
                            Key = "night_owl",
                            Name = "Night Owl"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0014-4000-8000-000000000014"),
                            Category = 3,
                            Description = "Complete a habit before 7 AM (UTC)",
                            Icon = "🐦",
                            Key = "early_bird",
                            Name = "Early Bird"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0015-4000-8000-000000000015"),
                            Category = 3,
                            Description = "Write 30 daily log entries",
                            Icon = "📝",
                            Key = "journal_keeper",
                            Name = "Journal Keeper"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0016-4000-8000-000000000016"),
                            Category = 3,
                            Description = "Reach Level 50",
                            Icon = "🎖️",
                            Key = "level_legend",
                            Name = "Level Legend"
                        });
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.DailyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("DailyLogs");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("✅");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.HabitEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("HabitId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("HabitId", "Date")
                        .IsUnique();

                    b.ToTable("HabitEntries");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GoalId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.QuestTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("QuestTaskListId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestTaskListId");

                    b.ToTable("QuestTasks");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.QuestTaskList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("QuestTaskLists");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique();

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.UserXp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserXps");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.XpTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Source", "ReferenceId");

                    b.ToTable("XpTransactions");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.DailyLog", b =>
                {
                    b.HasOne("QuestLog.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.Goal", b =>
                {
                    b.HasOne("QuestLog.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.Habit", b =>
                {
                    b.HasOne("QuestLog.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.HabitEntry", b =>
                {
                    b.HasOne("QuestLog.Domain.Entities.Habit", "Habit")
                        .WithMany("Entries")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.Milestone", b =>
                {
                    b.HasOne("QuestLog.Domain.Entities.Goal", "Goal")
                        .WithMany("Milestones")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.QuestTask", b =>
                {
                    b.HasOne("QuestLog.Domain.Entities.QuestTaskList", "QuestTaskList")
                        .WithMany("Tasks")
                        .HasForeignKey("QuestTaskListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestTaskList");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.QuestTaskList", b =>
                {
                    b.HasOne("QuestLog.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.UserAchievement", b =>
                {
                    b.HasOne("QuestLog.Domain.Entities.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestLog.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.UserXp", b =>
                {
                    b.HasOne("QuestLog.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.XpTransaction", b =>
                {
                    b.HasOne("QuestLog.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.Goal", b =>
                {
                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.Habit", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("QuestLog.Domain.Entities.QuestTaskList", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
